import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()
export default function Home({data}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    {
      data?.map((movie)=><p>{movie.title}</p>)
    }
      
    </div>
  )
}
export async function getServerSideProps(){
  const movies = await prisma.movie.findMany()
  return{
    props : {
      data: movies
    }
  }
}
